name: "Flutter Fastlane Action"
description: "GitHub Action to build and deploy Flutter apps using Fastlane(ios) and Shorebird(optional)"
author: "Charles Ifoegbu"
branding:
  icon: "smartphone"
  color: "blue"

inputs:
  workingDirectory:
    description: "Directory where your Flutter project is located"
    required: false
    default: "."
  androidReleaseOutput:
    description: "Path to the Android release output file (AAB)"
    required: false
    default: "build/app/outputs/bundle/release/app-release.aab"
  mappingFile:
    description: "Mapping file to use for android"
    required: false
    default: "build/app/outputs/mapping/release/mapping.txt"
  debugSymbols:
    description: "Debug symbols to use for android"
    required: false
    default: "build/app/intermediates/merged_native_libs/release/out/lib"
  playStoreWhatsNewDirectory:
    description: "Notes for the staged version of the app to show to users."
    required: false
    default: ""
  playStoreInAppUpdatePriority:
    description: "In-app update priority of the release"
    required: false
    default: "5"
  playStoreReleaseStatus:
    description: "Release status to use for android"
    required: false
    default: "completed"
  playStoreUserFraction:
    description: "Percentage of users who should get the staged version of the app."
    required: false
    # default: "0.99"
  matchGitBranch:
    description: "Git branch to use for fastlane match"
    required: false
    default: "master"
  platform:
    description: "Target platform (ios/android)"
    required: true
  androidBuildArgs:
    description: "Build arguments to use for android"
    required: false
    default: ""
  iosBuildArgs:
    description: "Build arguments to use for ios"
    required: false
    default: ""
  # iosChangelog:
  #   description: "Changelog to use for ios"
  #   required: false
  #   default: ""
  buildNumber:
    description: "Build number to use"
    required: false
  buildName:
    description: "Build name/version to use"
    required: false
  iosDistributionJson:
    description: "IOS secrets json to use. See README.md for more details"
    required: false
  isPatch:
    description: "Whether to use shorebird patch build(Note: This is only applicable to shorebird projects)"
    required: false
    default: "false"
  flutterVersion:
    description: "Flutter version to use"
    required: false
    default: "3.27.4"
  flutterChannel:
    description: "Flutter channel to use"
    required: false
    default: "stable"
  shorebirdToken:
    description: "Shorebird token to use"
    required: false
    default: ""
  useShorebird:
    description: "Whether to use shorebird"
    required: false
    default: "false"
  javaVersion:
    description: "Java version to use"
    required: false
    default: "17"
  packageName:
    description: "Package name for android"
    required: false
    default: ""
  bundleIdentifier:
    description: "Bundle identifier for ios"
    required: false
    default: ""
  track:
    description: "Track to use for play store deployment"
    required: false
    default: "internal"
  serviceAccountJsonPlainText:
    description: "Service account json plain text to use for play store deployment"
    required: false
    default: ""
  androidKeyStorePath:
    description: "Path to the android key store"
    required: false
    default: ""
  androidKeyStorePassword:
    description: "Password to the android key store"
    required: false
    default: ""
  androidKeyStoreAlias:
    description: "Alias to the android key store"
    required: false
    default: ""
  androidKeyPassword:
    description: "Password to the android key"
    required: false
    default: ""
  skipConfigureKeystore:
    description: "Skip keystore configuration (useful if keystore is already configured in the project)"
    required: false
    default: "false"
  withCache:
    description: "Whether to cache dependencies (pub, gradle, cocoapods)"
    required: false
    default: "false   "
runs:
  using: "composite"
  steps:
    - name: 🔧 Setup Environment Variables
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/setup_env_vars.sh \
          --is-patch "${{ inputs.isPatch }}" \
          --flutter-version "${{ inputs.flutterVersion }}" \
          --flutter-channel "${{ inputs.flutterChannel }}" \
          --build-name "${{ inputs.buildName }}" \
          --build-number "${{ inputs.buildNumber }}" \
          --platform "${{ inputs.platform }}" \
          --working-directory "${{ inputs.workingDirectory }}" \
          --shorebird-token "${{ inputs.shorebirdToken }}" \
          --use-shorebird "${{ inputs.useShorebird }}" \
          --android-key-store-path "${{ inputs.androidKeyStorePath }}" \
          --android-key-store-password "${{ inputs.androidKeyStorePassword }}" \
          --android-key-store-alias "${{ inputs.androidKeyStoreAlias }}" \
          --android-key-password "${{ inputs.androidKeyPassword }}" \
          --skip-configure-keystore "${{ inputs.skipConfigureKeystore }}" \
          --package-name "${{ inputs.packageName }}" \
          --build-args-android "${{ inputs.androidBuildArgs }}" \
          --build-args-ios "${{ inputs.iosBuildArgs }}" \
          --bundle-identifier "${{ inputs.bundleIdentifier }}" \
          --match-git-branch "${{ inputs.matchGitBranch }}" \
          --play-store-whatsnew-directory "${{ inputs.playStoreWhatsNewDirectory }}" \
          --service-account-json '${{ inputs.serviceAccountJsonPlainText }}' \
          --ios-secrets '${{ inputs.iosDistributionJson }}'

    - name: Validate Required Inputs
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/validate_inputs.sh

    - name: ☕ Change Java Version
      if: ${{ env.platform == 'android' }}
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "${{ inputs.javaVersion }}"

    - name: 📦 Cache Gradle Dependencies
      if: ${{ env.platform == 'android' && inputs.withCache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: 📦 Get Fastlane Configs and update ios folder
      working-directory: ${{ env.workingDir }}
      if: ${{ env.platform == 'ios' }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/get_fastlane_configs.sh '${{ inputs.iosDistributionJson }}'

    - name: 💎 Setup Ruby with ruby-build
      if: ${{ env.platform == 'ios' }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/install_ruby.sh

    - name: 📦 Cache CocoaPods Dependencies
      if: ${{ env.platform == 'ios' && inputs.withCache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.workingDir }}/ios/Pods
          ~/Library/Caches/CocoaPods
          ~/.cocoapods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: 📦 Install Fastlane Dependencies
      if: ${{ env.platform == 'ios' }}
      shell: bash
      working-directory: ${{ env.workingDir }}/ios
      run: |
        bundle install

    - name: 🐦 Setup Flutter
      shell: bash
      if: ${{ env.isShorebird == 'false' }}
      run: |
        ${{ github.action_path }}/scripts/install_flutter.sh

    - name: 🐦 Setup Shorebird
      shell: bash
      if: ${{ env.isShorebird == 'true' }}
      run: |
        ${{ github.action_path }}/scripts/install_shorebird.sh

    - name: 📦 Cache Pub Dependencies
      if: ${{ inputs.withCache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ env.workingDir }}/.dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: 🏗️ Build and Deploy iOS App (Testflight)
      shell: bash
      if: ${{ env.platform == 'ios' }}
      working-directory: ${{ env.workingDir }}/ios
      run: |
        bundle exec fastlane ios_testflight

    - name: 🏗️ Build Android App
      if: ${{ env.platform == 'android' }}
      working-directory: ${{ env.workingDir }}
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/android_build.sh

    - name: 🚀 Deploy to Google Play
      if: ${{ env.platform == 'android' && env.isPatch == 'false' }}
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ inputs.serviceAccountJsonPlainText }}
        packageName: ${{ inputs.packageName }}
        releaseFiles: ${{ env.workingDir }}/${{ inputs.androidReleaseOutput }}
        track: ${{ inputs.track }}
        status: ${{ inputs.playStoreReleaseStatus }}
        inAppUpdatePriority: ${{ inputs.playStoreInAppUpdatePriority }}
        whatsNewDirectory: ${{ env.playStoreWhatsNewDirectory }}
        userFraction: ${{ inputs.playStoreUserFraction }}
        mappingFile: ${{ env.workingDir }}/${{ inputs.mappingFile }}
        debugSymbols: ${{ env.workingDir }}/${{ inputs.debugSymbols }}

    - name: Clean up
      working-directory: ${{ env.workingDir }}/ios
      shell: bash
      if: ${{ env.platform == 'ios' && always()}}
      run: |
        ${{ github.action_path }}/scripts/clean_up.sh
