source "https://rubygems.org"

gem "fastlane"

# Fastlane plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# Additional gems for iOS deployment
gem "cocoapods", "1.16.2"
gem "xcodeproj", "~> 1.24"
