# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# Define keychain name as a variable to use throughout the file
keychain_name = "ifoegbu1_flutter_fastlane_keychain"

platform :ios do
  desc "Build and upload to TestFlight"
  lane :ios_testflight do
    create_keychain(
      name: keychain_name,
      default_keychain: false,
      unlock: true,
      timeout: 0,
      password: "#{keychain_name}-password",
      lock_when_sleeps: false
    )
   
    
    # Configure App Store Connect API Key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    if ENV["nukeMatch"] == "true"
      match_nuke(type: "appstore", 
      platform: "ios",
      skip_confirmation: true
      )
    end



    
    # Fetch certs & profiles for App Store distribution
    match(
      type: "appstore",  
      readonly: false,
      keychain_name: keychain_name,
      keychain_password: "#{keychain_name}-password",
      # platform: "ios",
      skip_confirmation: true
    )
    
    # Update Xcode project with Match profiles
      update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: ENV["sigh_#{ENV['BUNDLE_IDENTIFIER']}_appstore_profile-path"],
      target_filter: "Runner",
      build_configuration: "Release"
      )

      # Update code signing settings
      update_code_signing_settings(
        use_automatic_signing: false,
        team_id: ENV["TEAM_ID"],
        bundle_identifier: ENV["BUNDLE_IDENTIFIER"],
        profile_name:ENV["sigh_#{ENV['BUNDLE_IDENTIFIER']}_appstore_profile-name"],
        code_sign_identity: "Apple Distribution"
      )

      # sh "pod repo update"

      flutterV = ENV["flutterV"] 
      isPatch = ENV["isPatch"] || "false"
      isShorebird = ENV["isShorebird"] || "false"

      releaseV = ENV["releaseV"]

      if isShorebird == "true"
        sh "echo \"🐦 Shorebird action initiated\""
        if isPatch == "true"
          sh "echo \"🎯 Shorebird Patch action initiated\""
          patch_args = "--release-version #{releaseV} --allow-asset-diffs"
          
          # Add additional build arguments if available
        
          
          shorebird_patch(platform: "ios", args: patch_args, verbose: false)
        else
          sh "echo \"🚀 Shorebird Release action initiated\""
          flutter_args = "--no-tree-shake-icons"
          
          # Add build-name and build-number if available
          if ENV["buildName"]
            flutter_args += " --build-name=#{ENV["buildName"]}"
          end
          if ENV["buildNumber"]
            flutter_args += " --build-number=#{ENV["buildNumber"]}"
          end
          
          # Add additional build arguments if available
          if ENV["buildArgsIos"]
            flutter_args += " #{ENV["buildArgsIos"]}"
          end
          
          shorebird_release(
            platform: "ios", 
            args: "--flutter-version #{flutterV} -- #{flutter_args}",
            # verbose: true
          )
        end
      else
         sh "echo \"🚀 Building with Flutter version: #{flutterV}\""
      #       flutter_build(
      #   debug: true,

      #   build_number: ENV["buildNumber"],
      #   build_name: ENV["buildName"],

      #   build_args: (ENV["buildArgsIos"] || "").split,
      # )
       
        # Generate ExportOptions.plist from match signing configuration
        export_options_path = File.join(File.dirname(__FILE__), "ExportOptions.plist")
        profile_name = ENV["sigh_#{ENV['BUNDLE_IDENTIFIER']}_appstore_profile-name"]
        UI.user_error!("Provisioning profile name not found from match. Ensure match completed successfully.") unless profile_name
        export_options_plist = <<~PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>#{ENV['TEAM_ID']}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>#{ENV['BUNDLE_IDENTIFIER']}</key>
              <string>#{profile_name}</string>
            </dict>
          </dict>
          </plist>
        PLIST
        File.write(export_options_path, export_options_plist)
        
        build_cmd = "cd ../.. && flutter build ipa --release --export-options-plist=ios/fastlane/ExportOptions.plist"
        
        # Add build-name and build-number if available
        if ENV["buildName"]
          build_cmd += " --build-name=#{ENV["buildName"]}"
        end
        if ENV["buildNumber"]
          build_cmd += " --build-number=#{ENV["buildNumber"]}"
        end
        
        # Add additional build arguments if available
        if ENV["buildArgsIos"]
          build_cmd += " #{ENV["buildArgsIos"]}"
        end
        
        sh build_cmd
        # gym(
        #   workspace: "Runner.xcworkspace",
        #   scheme: "Runner",
        #   silent: true,
        #   suppress_xcode_output: true
        # )
      end
    




    # Upload to TestFlight
    if isPatch == "false"
      # Flutter outputs IPA to build/ios/ipa/ relative to project root
      # Dir.pwd is ios/fastlane/, so project root is two levels up
      ipa_dir = File.expand_path("../../build/ios/ipa", Dir.pwd)
      ipa_path = Dir["#{ipa_dir}/*.ipa"].first
      UI.user_error!("No IPA file found in #{ipa_dir}. Ensure flutter build ipa completed successfully.") unless ipa_path
      upload_to_testflight(
        ipa: ipa_path,
        skip_waiting_for_build_processing: true,
        # changelog: ENV["iosChangelog"]
      )
    end
  end

  
end

desc "delete created keychain"
   lane :delete_chain do
delete_keychain(name: "#{keychain_name}-db")
end