name: Flutter App Deployment Example
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
      IOS_DISTRIBUTION_JSON: ${{ secrets.IOS_DISTRIBUTION_JSON }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      PACKAGE_NAME: ${{ vars.PACKAGE_NAME }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  # Android deployment example
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the action to build and deploy
      - name: Build and deploy to Play Store
        uses: ifoegbu1/flutter-fastlane-action@v1
        with:
          platform: android
          buildNumber: ${{ github.run_number }}
          buildName: ${{ github.ref_name }}
          packageName: ${{ env.PACKAGE_NAME }}
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT_JSON }}
          androidKeyStorePath: "android/app/keystore.jks"
          androidKeyStorePassword: ${{ env.KEYSTORE_PASSWORD }}
          androidKeyStoreAlias: ${{ env.KEY_ALIAS }}
          androidKeyPassword: ${{ env.KEY_PASSWORD }}
          track: "internal"

  # iOS deployment example
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Use the action to build and deploy
      - name: Build and deploy to TestFlight
        uses: ifoegbu1/flutter-fastlane-action@v1
        with:
          platform: ios
          buildNumber: ${{ github.run_number }}
          buildName: ${{ github.ref_name }}
          iosDistributionJson: ${{ env.IOS_DISTRIBUTION_JSON }}
